getgenv().servicesTest = false -- Runs a fast test to see if all services work.

if not game:IsLoaded() then
    game.Loaded:Wait()
end

local Services = {
        AccountService = game:GetService("AccountService"),
        AchievementService = game:GetService("AchievementService"),
        AdService = game:GetService("AdService"),
        AnalyticsService = game:GetService("AnalyticsService"),
        AnimationClipProvider = game:GetService("AnimationClipProvider"),
        AppStorageService = game:GetService("AppStorageService"),
        AppUpdateService = game:GetService("AppUpdateService"),
        AssetService = game:GetService("AssetService"),
        AvatarChatService = game:GetService("AvatarChatService"),
        AvatarCreationService = game:GetService("AvatarCreationService"),
        AvatarEditorService = game:GetService("AvatarEditorService"),
        BadgeService = game:GetService("BadgeService"),
        BrowserService = game:GetService("BrowserService"),
        CaptureService = game:GetService("CaptureService"),
        ChangeHistoryService = game:GetService("ChangeHistoryService"),
        Chat = game:GetService("Chat"),
        CollectionService = game:GetService("CollectionService"),
        CommerceService = game:GetService("CommerceService"),
        ContentProvider = game:GetService("ContentProvider"),
        ContextActionService = game:GetService("ContextActionService"),
        ControllerService = game:GetService("ControllerService"),
        CookiesService = game:GetService("CookiesService"),
        CoreGui = game:GetService("CoreGui"),
        CorePackages = game:GetService("CorePackages"),
        DataModelPatchService = game:GetService("DataModelPatchService"),
        DataStoreService = game:GetService("DataStoreService"),
        Debris = game:GetService("Debris"),
        EventIngestService = game:GetService("EventIngestService"),
        ExperienceAuthService = game:GetService("ExperienceAuthService"),
        ExperienceNotificationService = game:GetService("ExperienceNotificationService"),
        ExperienceService = game:GetService("ExperienceService"),
        ExperienceStateCaptureService = game:GetService("ExperienceStateCaptureService"),
        FaceAnimatorService = game:GetService("FaceAnimatorService"),
        FacialAnimationStreamingServiceV2 = game:GetService("FacialAnimationStreamingServiceV2"),
        FriendService = game:GetService("FriendService"),
        GamePassService = game:GetService("GamePassService"),
        GamepadService = game:GetService("GamepadService"),
        GeometryService = game:GetService("GeometryService"),
        GroupService = game:GetService("GroupService"),
        GuiService = game:GetService("GuiService"),
        GuidRegistryService = game:GetService("GuidRegistryService"),
        HSRDataContentProvider = game:GetService("HSRDataContentProvider"),
        HapticService = game:GetService("HapticService"),
        HeatmapService = game:GetService("HeatmapService"),
        HttpRbxApiService = game:GetService("HttpRbxApiService"),
        HttpService = game:GetService("HttpService"),
        IXPService = game:GetService("IXPService"),
        InsertService = game:GetService("InsertService"),
        JointsService = game:GetService("JointsService"),
        KeyboardService = game:GetService("KeyboardService"),
        KeyframeSequenceProvider = game:GetService("KeyframeSequenceProvider"),
        Lighting = game:GetService("Lighting"),
        LinkingService = game:GetService("LinkingService"),
        LocalizationService = game:GetService("LocalizationService"),
        LogService = game:GetService("LogService"),
        MarketplaceService = game:GetService("MarketplaceService"),
        MaterialService = game:GetService("MaterialService"),
        MemStorageService = game:GetService("MemStorageService"),
        MemoryStoreService = game:GetService("MemoryStoreService"),
        MeshContentProvider = game:GetService("MeshContentProvider"),
        MessageBusService = game:GetService("MessageBusService"),
        MessagingService = game:GetService("MessagingService"),
        MouseService = game:GetService("MouseService"),
        NetworkClient = game:GetService("NetworkClient"),
        NotificationService = game:GetService("NotificationService"),
        OmniRecommendationsService = game:GetService("OmniRecommendationsService"),
        OpenCloudService = game:GetService("OpenCloudService"),
        PermissionsService = game:GetService("PermissionsService"),
        PhysicsService = game:GetService("PhysicsService"),
        PlatformCloudStorageService = game:GetService("PlatformCloudStorageService"),
        PlatformFriendsService = game:GetService("PlatformFriendsService"),
        PlayerEmulatorService = game:GetService("PlayerEmulatorService"),
        PlayerViewService = game:GetService("PlayerViewService"),
        Players = game:GetService("Players"),
        PointsService = game:GetService("PointsService"),
        PolicyService = game:GetService("PolicyService"),
        ProximityPromptService = game:GetService("ProximityPromptService"),
        RbxAnalyticsService = game:GetService("RbxAnalyticsService"),
        ReplicatedFirst = game:GetService("ReplicatedFirst"),
        ReplicatedStorage = game:GetService("ReplicatedStorage"),
        RobloxReplicatedStorage = game:GetService("RobloxReplicatedStorage"),
        RobloxServerStorage = game:GetService("RobloxServerStorage"),
        RtMessagingService = game:GetService("RtMessagingService"),
        RunService = game:GetService("RunService"),
        RuntimeScriptService = game:GetService("RuntimeScriptService"),
        SafetyService = game:GetService("SafetyService"),
        ScriptContext = game:GetService("ScriptContext"),
        ScriptProfilerService = game:GetService("ScriptProfilerService"),
        ScriptRegistrationService = game:GetService("ScriptRegistrationService"),
        ScriptService = game:GetService("ScriptService"),
        Selection = game:GetService("Selection"),
        SessionService = game:GetService("SessionService"),
        SharedTableRegistry = game:GetService("SharedTableRegistry"),
        SocialService = game:GetService("SocialService"),
        SolidModelContentProvider = game:GetService("SolidModelContentProvider"),
        SoundService = game:GetService("SoundService"),
        SpawnerService = game:GetService("SpawnerService"),
        StarterGui = game:GetService("StarterGui"),
        StarterPack = game:GetService("StarterPack"),
        StarterPlayer = game:GetService("StarterPlayer"),
        Stats = game:GetService("Stats"),
        StudioData = game:GetService("StudioData"),
        StylingService = game:GetService("StylingService"),
        Teams = game:GetService("Teams"),
        TeleportService = game:GetService("TeleportService"),
        TestService = game:GetService("TestService"),
        TextBoxService = game:GetService("TextBoxService"),
        TextChatService = game:GetService("TextChatService"),
        TextService = game:GetService("TextService"),
        ThirdPartyUserService = game:GetService("ThirdPartyUserService"),
        TimerService = game:GetService("TimerService"),
        TouchInputService = game:GetService("TouchInputService"),
        TweenService = game:GetService("TweenService"),
        UserInputService = game:GetService("UserInputService"),
        UserService = game:GetService("UserService"),
        VRService = game:GetService("VRService"),
        VideoCaptureService = game:GetService("VideoCaptureService"),
        Visit = game:GetService("Visit"),
        VoiceChatService = game:GetService("VoiceChatService"),
        Workspace = game:GetService("Workspace")
}

local Utils = {}

Utils.lineBreak = function(amt) amt = amt or 1 for i = 1, amt do print("\n") end end

if servicesTest == true then print "running services test" Utils.lineBreak() for i, v in pairs(Services) do print(i .. " = " .. tostring(v)) end Utils.lineBreak() end

return { Services, Utils }
